### ISSUE TITLE
npm install报错

### ISSUE THREAD

**Issue by cm971991** [SmallRuralDog/electron-vue-music#2]
13523 silly saveTree     `-- yargs-parser@7.0.0
13524 warn dog-music@0.1.0 No repository field.
13525 warn dog-music@0.1.0 No license field.
13526 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '....2"},"modified":"2015'
13526 verbose stack     at JSON.parse (<anonymous>)
13526 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-better-errors\index.js:7:17)
13526 verbose stack     at consumeBody.call.then.buffer (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
13526 verbose stack     at <anonymous>
13526 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
13527 verbose cwd E:\code\demo\electron-vue-music
13528 verbose Windows_NT 10.0.17134
13529 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
13530 verbose node v8.11.2
13531 verbose npm  v5.6.0
13532 error Unexpected end of JSON input while parsing near '....2"},"modified":"2015'
13533 verbose exit [ 1, true ]

**Comment by fakaka** [comment]
用 yarn 试试

**Comment by 45281625** [comment]
推荐用cnpm

**Comment by jiaoyinheshaoxu** [comment]
个人推荐用 yarn , cnpm 也可以

**Comment by wedreamer** [comment]
cnpm 就好啦

**Comment by hsj-xiaokang** [comment]
删除依赖重试几次就OK了

**Comment by waterone** [comment]
请问一下npm install 之后它会下载一个electron-v1.8.7-win32-x64.zip的吗？

**Comment by SUNbrightness** [comment]
cnpm 好使!!!

**Comment by ShuangDa1018** [comment]
> > electron@1.8.7 postinstall D:\tanshuang\electron\electron-vue-music-master\node_modules\electron
> node install.js

Downloading SHASUMS256.txt
[============================================>] 100.0% (14.75 kB/s)
D:\tanshuang\electron\electron-vue-music-master\node_modules\electron\install.js:47    
  throw err
  ^

Error: Could not parse checksum file at line 1: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">    
    at new ChecksumParseError (D:\tanshuang\electron\electron-vue-music-master\node_modules\sumchecker\build.js:71:127)
    at D:\tanshuang\electron\electron-vue-music-master\node_modules\sumchecker\build.js:130:20
    at Array.forEach (<anonymous>)
    at D:\tanshuang\electron\electron-vue-music-master\node_modules\sumchecker\build.js:125:38
    at new Promise (<anonymous>)
    at ChecksumValidator.parseChecksumFile (D:\tanshuang\electron\electron-vue-music-master\node_modules\sumchecker\build.js:121:14) {
  line: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">'
}
npm WARN dog-music@0.1.3 No repository field.
npm WARN dog-music@0.1.3 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.7 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.8.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TWX1039639\AppData\Roaming\npm-cache\_logs\2021-08-25T02_10_08_921Z-debug.log
