### ISSUE TITLE
npm run dev的时候报了这个错

### ISSUE THREAD

**Issue by zhangyanling77** [SmallRuralDog/electron-vue-music#6]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::9080
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at Server.listen (/Users/zhangyanling/Desktop/electron-vue-music/node_modules/webpack-dev-server/lib/Server.js:570:41)
    at Promise (/Users/zhangyanling/Desktop/electron-vue-music/.electron-vue/dev-runner.js:76:12)
    at new Promise (<anonymous>)
    at startRenderer (/Users/zhangyanling/Desktop/electron-vue-music/.electron-vue/dev-runner.js:42:10)
    at init (/Users/zhangyanling/Desktop/electron-vue-music/.electron-vue/dev-runner.js:169:16)
    at Object.<anonymous> (/Users/zhangyanling/Desktop/electron-vue-music/.electron-vue/dev-runner.js:178:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dog-music@0.1.3 dev: `node .electron-vue/dev-runner.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dog-music@0.1.3 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by zhangyanling77** [comment]
已经解决了。。
